addSbtPlugin("com.timushev.sbt"          % "sbt-updates"         % "0.4.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.0.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.7")
addSbtPlugin("io.spray"                  % "sbt-revolver"        % "0.9.1")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.4.1")
